#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Persistent
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#MaxThreadsPerHotkey 2

F4::
{
	sleep, 5000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 10000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	; Rocket League Press Any Button to Start

	sleep, 70000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	; Skip Tutorial
   
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	sleep, 500
	MouseClick, right
	; Skip Goal Replays

	sleep, 1000
	Send {enter}
	Send, {Space}
	MouseClick, right
	sleep, 3000
	Send {enter}
	Send, {Space}
	MouseClick, right
	; Go to Main Menu
	
}
Return